version: '3'
services:
  node-init:
    container_name: feedme-tha
    image: feedme-tha:dev
    build:
      context: ./
      dockerfile: ./Dockerfiles/FeedMeTHADev
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - ./routes:/usr/src/app/routes
      - ./views:/usr/src/app/views
      - ./public/scripts:/usr/src/app/public/scripts

